### ISSUE TITLE
Tutorial in tests

### ISSUE THREAD

**Issue by erjank** [cmelab/flowerMD#20]
Should have the test suite run through the tutorial notebook to make sure there's no importing or syntax errors.

**Comment by chrisjonesBSU** [comment]
@marjanAlbouye I noticed we added NBReview now. Does that solve this issue? I'll have to do some googling to see how to include notebooks in unit tests.

**Comment by marjanAlbouye** [comment]
> @marjanAlbouye I noticed we added NBReview now. Does that solve this issue? I'll have to do some googling to see how to include notebooks in unit tests.

Yeah, looks like we have NBReview for all the repositories in cmelab space but I'm not sure how it works exactly. It might show up in our next PR where there's actually a change in one of the notebooks.
