### ISSUE TITLE
Make GPU and CPU containers

### ISSUE THREAD

**Issue by chrisjonesBSU** [cmelab/flowerMD#28]
While the environment is relatively simple to set up, I think it is still worth while to have containers made since computer clusters (and Anaconda) can be unpredictable. Plus, there are some annoying steps required to get the GPU version of hoomd via conda when on a head node that would be nice to skip in a workshop type setting.

We should have one using the CPU environment and one using the GPU environment.

**Comment by RainierBarrett** [comment]
As per discussion today, we probably only need the GPU-capable container which has a superset of the CPU container ability.
