### ISSUE TITLE
Solve Pytest caching 

### ISSUE THREAD

**Issue by marjanAlbouye** [cmelab/flowerMD#48]
It seems that in some of the unit tests, the variables are being cached, which causes some tests that expect a different behavior from a cached value fail.
Check `test_update_volume_with_density_no_ref_values` in `test_simulation.py` for an example.  The test is commented now. In this test, the `sim_no_ref` variable is being loaded from the cache rather than being instantiated in the method, which makes the test fail. This is because  the test requires `sim_no_ref` to not have `reference_values` but the cached object already has them.

My first guess is Pytest fixtures are being cached and since we use those fixtures to instantiate a variable like `sim_no_ref` the objects are cached too. 

Some things to try:

- Use `yield` instead of `return` in fixture methods
- Uitilize pytest Teardown to clear cache

**Comment by chrisjonesBSU** [comment]
Are you still experiencing this problem @marjanAlbouye I haven't had it happen to me when running pytest locally, and the last few PRs seem to get through all the tests without any issue.

**Comment by marjanAlbouye** [comment]
Yes, the problem's still there. I just commented the unit test that causes this. The unit test is `test_update_volume_with_density_no_ref_values` in `test_simulation.py`.

**Comment by chrisjonesBSU** [comment]
I think we figured out 2 things. 1) This is an issue with pytest in genreal, and after looking around, I don't think there is any magic fix we can do at the pytest level. 2) So far, most of the issues have gone away by explicitly passing in all of the parameters when initializing new classes (e.g. using `base_units=dict()` when making a new `System` class.)

I think we can close this for now.
